dist: trusty
language: php

php:
  - 7.2
  - 7.3
  - 7.4

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

# fails because psr12 isn't available on lowest version
# TODO re-enable --prefer-lowest test without running check-style
# matrix:
  # include:
    # - php: 7.2
      # env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

before_script:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - composer check-style
  - composer test
